### ISSUE TITLE
Wifi Pet Feeder (PetLibro) feeding on reconnect

### ISSUE THREAD

**Issue by reclaimer5146** [rospogrigio/localtuya-homeassistant#1082]
## The problem
 
This is a new setup.

I have a [PetLibro WiFi Pet Feeder](https://www.amazon.com/gp/product/B097H1QDTY). I can add it into LocalTuya and it works but with some issues. With "number" entity for feeding, it feeds when I reconnect the device or restart HA due to marking it as passive (more info below). If I setup a switch entity for feeding, the toggle only causes it to feed nonstop (more info below). Automations work, the issue is that when the device reconnects it either doesn't feed or feeds again when it shouldn't depending on the config (again, more below)

- DP 3 (Manual Feed) and DP 15 (Feed Report) do not show after the device has been rebooted. As per the documentation, can be resolved by opening SmartLife and initiating a feed. Feeding from the app initiates DP 3 and DP 15. If I feed from the manual button on device, it only initiates DP 15.

- Setup as a number entity it almost works perfectly. Max and Min values for DP 3 are 0-12. I can slide and it will feed the amount. However, if I set to 0, it feeds non stop and I have to unplug the device to stop it. I can somewhat fix that by setting limits to 1-12. But if I reboot the device, DP 3 and 15 are gone again. Only way to have DP 3 there and functional after reboot is to set as passive. Unfortunately, setting the entity to passive causes the feeder to feed anytime it reconnect to HA, whether it be due to a reboot of HA, loss of connectivity, or the device itself rebooting. It only feeds once.

- Adding DP 3 as a switch (nothing added other than name) works to feed as well, however, it's always on. If I try to toggle it, it just feeds non stop, similar to if I set the value to 0 above.

I've tried to set the default value (when not initialized) as 0 when a number entity, but as mentioned, it will only cause it to go non stop unless I reboot the device. I would like to get this setup under "number" entity, but can figure something out via automation if another entity type needs to be used.

All DP monitoring is being done with TinyTuya via simple python script.

I tried to explain it as best as I could without being wordy, please let me know if you need a better summary.
## Environment

- Localtuya version: 4.1.1  
- Last working localtuya version (if known and relevant): N/A, this is a new setup.
- Home Assistant Core version: Home Assistant 2022.10.3, Supervisor 2022.10.0, Operating system 9.2, Frontend 20221010.0-latest 
- [] Are you using the Home Assistant Tuya Cloud component ? No 
- [x] Are you using the Tuya App in parallel ? Not actively, just for initial setup and to initialize DP 3 and DP 15. No scenes or meal plans are configured in app. App is not open while testing in localtuya. 

## Steps to reproduce

**Reproduce feeding not working after device reboot (non-passive entity)**
1. Setup Feeder with DP 3 as "number" entity. Min 1, Max 12, Min increment 1. Do NOT set passive entity.
2. Reboot Feeder
3. Attempt to feed. DP 3 and DP 15 are disabled until you go into SmartLife app and feed manually once.

**Reproduce feeding when device reconnects after reboot, HA restart, or connectivity loss (passive entity)**
1. Setup Feeder with DP 3 as "number" entity. Min 1, Max 12, Min increment 1. Set Passive Entity
2.  Reboot Feeder
3. On reconnect, feeder will feed 1 portion, which it shouldn't do. As passive, DP 3 and 15 will now be available (which is why I think it's feeding on reconnect)

**Reproduce "number" entity non stop feeding when set to 0.**
1. Setup Feeder with DP 3 as "number" entity. Min 0, Max 12, Min increment 1. Optionally, set Default value to 0
2. Using number entity slider, slide to 0 (if the default value of 0 hasn't already kicked in)
3. Feeder will continue non stop until unplugged. Hence why set min to 1 instead of 0 in above reproduction.

Reproduce using switch entity instead
1. Setup feeder with DP 3 as "switch" entity. Only changed name, left the rest as is.
2. Try to toggle switch for feeding
3. When toggled, feeder continues non stop.

## Configuration `configuration.yaml` or `config_flow`

```yaml
# Loads default set of integrations. Do not remove.
default_config:
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.8.1
  ip_ban_enabled: true
  login_attempts_threshold: 5
# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: !secret mariadb_url

# Telegram bot
telegram_bot:
    - platform: polling
      api_key: !secret telegram_bot_api_key
      allowed_chat_ids: !secret telegram_bot_chat_ids

# Notification Channels
notify:
    - platform: telegram
      name: telegram
      chat_id: !secret telegram_bot_my_chat_id
```

## DP dump

Couldn't figure out how to get the tuyadebug to work. Kept hitting different errors. These are the outputs from my tinytuya python script and I cross referenced them on the Tuya IoT platform via API explorer and dev console.

Device status: {'dps': {'3': 1, '4': 'standby', '9': False, '14': 0, '15': 1}}

DP 1: Meal Plan. Only exists when initiated from the app and then goes away
DP 3: Manual Feed. Numerical Value, 0-12. App doesn't allow for 0 but per Tuya IoT 0 is the minimum. The only DP that actually feeds
DP 4: Feed State. Only "standby" or "feeding" values.
DP 9: Factory Reset. Only true/false. Set to false since it's configured.
DP 14: Fault state. Not sure what this one is, haven't been able to get it to change at all even with swapping out batteries or trying to jam the feeder. There's no sensors for feed or jammed food either. 
DP 15: Feed Report. Reports how many servings were in the last feeding.

## Provide Home Assistant taceback/logs

```txt

```
## Additional information

Lots of words and info. I know it's a lot, but wanted to present as much as possible. Please let me know if there is anything else you need or if any clarifications are needed.
