### ISSUE TITLE
set_dp does not work if using template

### ISSUE THREAD

**Issue by dimonb** [rospogrigio/localtuya-homeassistant#1817]
## The problem
when using template, set_dp does not work

template example
```yaml
action: localtuya.set_dp
data:
  device_id: bf4b09608f0275c46a1ttg
  dp: 201
  value: >-
    {"control":"send_ir","head":"010ece0000000000040014003e00ab00ca","key1":"{{ packet }}","type":0,"delay":300}
```

## Environment

- Localtuya version: 5.2.2
- Home Assistant Core version: 2024.9.3

## Steps to reproduce

1. create script with template inside which execute set_dp command with json value
2. run it
3. nothing happen

## Additional information
```python
    async def set_dp(self, value, dp_index):
        """
        Set value (may be any type: bool, int or string) of any dps index.

        Args:
            dp_index(int):   dps index to set
            value: new value for the dps index
        """
        if isinstance(value, dict):
            value = json.dumps(value)
```
in case of template value came as dictionary and all things are broken. This small patch of pytuya.\_\_init\_\_.py fixes this issue
