### ISSUE TITLE
Suggestion to move YAML configuration to component

### ISSUE THREAD

**Issue by postlund** [rospogrigio/localtuya-homeassistant#22]
Currently we define new entities on platform level like this:

```yaml
switch:
  - platform: localtuya
    host: 192.168.0.1
    local_key: 1234567891234567
    device_id: 12345678912345671234
    name: tuya_01
    friendly_name: tuya_01
    protocol_version: 3.3
    current: 18
    current_consumption: 19
    voltage: 20
```
We also support two notions (in some case), where a single device can be defined "directly" but two or more are defined under another key, e.g. `switches:` like this:

```yaml
switch:
 - platform: localtuya
    host: 192.168.0.1
    local_key: 1234567891234567
    device_id: 12345678912345671234
    name: tuya_01
    friendly_name: tuya_01
    protocol_version: 3.3
    switches:
      sw01:
        name: main_plug
        friendly_name: Main Plug
        id: 1
        current: 18
        current_consumption: 19
        voltage: 20
      sw02:
        name: usb_plug
        friendly_name: USB Plug
        id: 7  
```
This has a few cons, e.g. not being consistent and you can't mix different platforms for the same device. I suggest that we move all configuration to the component so we can write something like this:

```yaml
localtuya:
    host: 192.168.0.1
    local_key: 1234567891234567
    device_id: 12345678912345671234
    name: tuya_01
    protocol_version: 3.3
    entities:
      - platform: switch
        friendly_name: Main Plug
        id: 1
        current: 18
        current_consumption: 19
        voltage: 20
      - platform: switch
        friendly_name: USB Plug
        id: 7  
```
This provides a consistent configuration interface which also maps directly to how config entries work. It would be a big breaking change, but would be a good one.

**Comment by rospogrigio** [comment]
Big thumb up for this, I'd say this would be the very next step. Switch configuration actually would become something like this (once we introduce the **sensor** platform):
```
localtuya:
    host: 192.168.0.1
    local_key: 1234567891234567
    device_id: 12345678912345671234
    friendly_name: Smart Plug Wifi
    protocol_version: 3.3
    entities:
      - platform: switch
        friendly_name: Main Plug
        id: 1
      - platform: switch
        friendly_name: USB Plug
        id: 7  
      - platform: sensor
        friendly_name: Plug Current
        id: 18
      - platform: sensor
        friendly_name: Plug Current Consumption
        id: 19
      - platform: sensor
        friendly_name: Plug Voltage
        id: 20
```
