### ISSUE TITLE
Multiple devices for Configuration.yaml

### ISSUE THREAD

**Issue by gogreenpower** [rospogrigio/localtuya-homeassistant#589]
## The problem

I have added 4 devices in my configuration.yaml, but only 1 or 2 is ever connected in HA, all entities show but the others are unavailable. when restarting is a random one each time that connects

## Environment

- Localtuya version:  
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version: core-2021.10.0 
- [] Are you using the Home Assistant Tuya Cloud component ? 
1. Add 2 or more devices via yaml
2. and restart HA

## Configuration `configuration.yaml`
```yaml
   - host: 192.168.1.10
    device_id: 1111111
    local_key: 1111111
    friendly_name: Dishwasher Wifi Power Switch
    protocol_version: "3.3"
    entities:
      - platform: sensor
        friendly_name: Dishwasher Current
        id: 18
        scaling: 0.1
        device_class: current
        unit_of_measurement: "A"
      - platform: sensor
        friendly_name: Dishwasher Power
        id: 19
        scaling: 0.1
        device_class: power
        unit_of_measurement: "W"
      - platform: sensor
        friendly_name: Dishwasher Voltage
        id: 20
        scaling: 0.1
        device_class: voltage
        unit_of_measurement: "V"
      - platform: switch
        friendly_name: Dishwasher Switch
        id: 1
  - host: 192.168.1.11
    device_id: 222222222
    local_key: 2222222
    friendly_name: Spare Wifi Power Switch
    protocol_version: "3.3"
    entities:
      - platform: sensor
        friendly_name: Spare Current
        id: 18
        scaling: 0.1
        device_class: current
        unit_of_measurement: "A"
      - platform: sensor
        friendly_name: Spare Power
        id: 19
        scaling: 0.1
        device_class: power
        unit_of_measurement: "W"
      - platform: sensor
        friendly_name: Spare Voltage
        id: 20
        scaling: 0.1
        device_class: voltage
        unit_of_measurement: "V"
      - platform: switch
        friendly_name: Spare Switch
        id: 1
  - host: 192.168.1.12
    device_id: 33333333
    local_key: 33333333
    friendly_name: Couch Lamp Port
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: Couch Lamp Port Switch
        id: 1
  - host: 192.168.1.13
    device_id: 444444
    local_key: 4444444
    friendly_name: Couch Lamp Starboard
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: Couch Lamp Starboard Switch
        id: 1
```
